#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry ' '{
  true
  }
menuentry '=== ISO utilities ==='{
  true
  }
menuentry "Rescatux 0.41B1" --class debian {
  set isofile="/boot/rescatux-0.41b1.iso"
  loopback loop (hd0,1)$isofile
  linux (loop)/live/vmlinuz1 boot=live findiso=${isofile} components
  initrd (loop)/live/initrd1.img
}
menuentry "Kali 2017.1" --class kali {
  set isofile="/boot/kali-linux-2017.1-amd64.iso"
  loopback loop (hd0,1)$isofile
  linux (loop)/live/vmlinuz-4.9.0-kali3-amd64 boot=live findiso=${isofile} boot=live components splash username=root hostname=kali noswap noautomount
  initrd (loop)/live/initrd.img-4.9.0-kali3-amd64
}
menuentry "Tails 3.1" --class debian {
  set isofile="/boot/tails-amd64-3.1.iso"
  loopback loop (hd0,1)$isofile
  linux (loop)/live/vmlinuz boot=live findiso=${isofile} components
  initrd (loop)/live/initrd.img
}
menuentry ' '{
  true
  }
menuentry '=== Memtest ==='{
  true
  }
